# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds', models.IntegerField()),
                ('ad_id', models.CharField(max_length=32)),
                ('item_id', models.CharField(max_length=128)),
                ('ad_name', models.TextField(null=True)),
                ('coupon_value', models.FloatField()),
                ('price', models.FloatField()),
                ('img_url', models.URLField()),
                ('coupon_url', models.URLField()),
                ('c1', models.IntegerField()),
                ('sales_num', models.IntegerField()),
            ],
        ),
    ]
