# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwxk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds', models.IntegerField()),
                ('brand_id', models.CharField(max_length=32)),
                ('brand_name', models.TextField(null=True)),
                ('brand_logo', models.URLField()),
            ],
        ),
    ]
