# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwxk', '0002_brandinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds', models.IntegerField()),
                ('ad_id', models.CharField(max_length=32)),
                ('ad_name', models.TextField(null=True)),
                ('coupon_value', models.FloatField()),
                ('price', models.FloatField()),
                ('img_url', models.URLField()),
                ('coupon_url', models.URLField()),
                ('brand_id', models.IntegerField()),
                ('sales_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds', models.IntegerField()),
                ('ad_id', models.CharField(max_length=32)),
                ('ad_name', models.TextField(null=True)),
                ('coupon_value', models.FloatField()),
                ('price', models.FloatField()),
                ('img_url', models.URLField()),
                ('coupon_url', models.URLField()),
                ('c1', models.IntegerField()),
                ('sales_num', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ItemsInfo',
        ),
    ]
