# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwxk', '0005_auto_20170720_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds', models.IntegerField()),
                ('keyword', models.TextField(null=True)),
                ('img_url', models.URLField()),
            ],
        ),
    ]
