# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwxk', '0006_bannerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfo',
            name='brand_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
