# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwxk', '0007_bannerinfo_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerinfo',
            old_name='brand_id',
            new_name='banner_id',
        ),
    ]
