# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwxk', '0009_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
