# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwxk', '0010_auto_20170722_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_get',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_give',
            field=models.IntegerField(default=0),
        ),
    ]
